resources:
  - ../../base
  - service.yaml

namePrefix: argo-

patches:
  - path: deployment_patch.yaml
    target:
      version: v0
      group: apps
      kind: Deployment
      name: teamx-gitops-simple-app
