resources:
  - ../../base

namePrefix: argo-

patches:
  - path: deployment_patch.yaml
    target:
      version: v1
      group: apps
      kind: Deployment
      name: teamx-gitops-simple-app
  - path: service_patch.yaml
    target:
      version: v1
      kind: Service
      name: teamx-gitops-simple-app

