apiVersion: v1
kind: Service
metadata:
  name: teamx-gitops-simple-app
  namespace: teamx
spec:
  selector:
    app: teamx-gitops-simple-app
  ports:
    - port: 8080
      nodePort: 30444
      targetPort: 8080
  type: NodePort