resources:
  - ../../base
  - service.yaml

patches:
  - path: deployment_patch.yaml
    target:
      version: v1
      group: apps
      kind: Deployment
      name: teamx-gitops-simple-app

namePrefix: circle-
