apiVersion: v1
kind: Service
metadata:
  name: teamx-gitops-simple-argo
  namespace: teamx
spec:
  selector:
    app: teamx-gitops-simple-argo
  ports:
    - port: 8080
      nodePort: 30445
      targetPort: 8080
  type: NodePort